### ISSUE TITLE
My version

### ISSUE THREAD

**Issue by gandaldf** [celsomtrindade/Affix#1]
After some tests I wasn't be able to use your directive, so I changed it a bit to fit my needs; this is my version with offsetTop and resize support:

```
.directive('affixMe', ['$window', function($window) {
    return {
        restrict: 'A',
        link: function(scope, element, attrs) {
            var child = element.children(0);
            var childOffset = child.offset();
            var offsetTop = attrs.offsetTop ? attrs.offsetTop : childOffset.top;

            function resizeChild(e, c) {
                c.width(e.width());
            }

            angular.element(document).ready(function() {
                resizeChild(element, child);
            });

            angular.element($window).bind('resize', function() {
                resizeChild(element, child);
            });

            angular.element($window).bind('scroll', function() {
                if (this.pageYOffset >= offsetTop) {
                    child.addClass('affix');
                } else {
                    child.removeClass('affix');
                }
            });
        }
    };
}]);
```

Use it this way:

```
<div data-affix-me data-offset-top="67">
    <div>
        <!-- div to affix -->
    </div>
</div>
```

**Comment by celsomtrindade** [comment]
With this, it won't need to have a `top` property in the `css`, am I right?

**Comment by gandaldf** [comment]
No... You'll need it anyway:

```
.affix {
    top: 80px;
}
```

because this define the div final position when affix is active.
With my solution you can define when, during the scrolling, the affix will be activated; and, in case of parent resizing, the child will be update accordingly.

Anyway... my code is just an advice, it uses a little jQuery here and there to keep the code cleaner, so it's not fully consistent with your project purpose (pure Javascript without external libraries); this is why I posted it here and I didn't forked it.

Soon I will expand it with bottom offset support.

**Comment by celsomtrindade** [comment]
I was studying your code and trying to mix with mine. I think I'll have a good result!!
And i think there is no problem with your code using jQuery functions. As long as they are in the native Angular jQlite, there is no problem. The main problem i was found was the need to include the jQuery main library. This is what i want to avoid.

**Comment by gandaldf** [comment]
This version doesn't rely on jQuery:

```
.directive('sticky', ['$window', function($window) {
return {
    restrict: 'A',
    link: function(scope, element, attrs) {
        var child = element.children(0);
        var childOffset = elementOffset(child);
        var offsetTop = attrs.offsetTop ? attrs.offsetTop : childOffset.top;

        function elementOffset(element)
        {
            var de = document.documentElement;
            var box = element[0].getBoundingClientRect();
            var top = box.top + window.pageYOffset - de.clientTop;
            var left = box.left + window.pageXOffset - de.clientLeft;
            return { top: top, left: left };
        }

        function resizeChild(e, c) {
            c.css({width: e[0].offsetWidth + 'px'});
        }

        angular.element(document).ready(function() {
            resizeChild(element, child);
        });

        angular.element($window).on('resize', function() {
            resizeChild(element, child);
        });

        angular.element($window).on('scroll', function() {
            if (this.pageYOffset >= offsetTop) {
                child.addClass('sticky');
            } else {
                child.removeClass('sticky');
            }
        });
    }
};
}]);
```

and here is my test plunk: http://plnkr.co/edit/35UQ1TtercCEHIXe4x1I?p=preview

**Comment by celsomtrindade** [comment]
After some review/research, I came with other piece of code to solve some issues I had. With your code, depending on the design, it was with a different offset top then the original, so it wasn't working well. I think everything is fine now.

Thanks for your help!
