### ISSUE TITLE
parentClass and childClass

### ISSUE THREAD

**Issue by Princeyadav05** [celsomtrindade/Affix#3]
Hey.
Really liked your work here. But what should be there in parentClass and childClass.
what should be their CSS.
I mean I dont want to specify any CSS, then what should be done ?

**Comment by celsomtrindade** [comment]
It's just classes you may want to use to style the elements. The only required thing to do is to add `position: relative` on the element where it has `parentClass`.

Also, make sure to include the `css` class affix on the `index.html` file because it controls the `affix` element.
